# Logstash Configuration for Galah Honeypot
http.host: "0.0.0.0"
http.port: 9600

# Pipeline settings
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# Path settings
path.config: "/usr/share/logstash/pipeline"
path.data: "/usr/share/logstash/data"
path.logs: "/usr/share/logstash/logs"

# Monitoring
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "${ELASTIC_PASSWORD}"

# Logging
log.level: info
